add html
Spartanek/iceCream-teamProjekt pull request #3
Opened 2024-03-17 09:56 UTC by Nekit2501

дадав поки тільки HTML чекаю інші елементи для подальшої роботи поку буду по трохи верстати SCSSS

2024-03-17 10:00 UTC, Spartanek commented on src/partials/mobile-menu.html
> +<div class="mob-menu is-hidden">
Є is-hidden але може краще visually-hidden

2024-03-17 10:01 UTC, Spartanek commented on src/partials/mobile-menu.html
> +<ul class="mob-menu">
краще клас ul дати mob-menu-list

2024-03-17 10:04 UTC, Spartanek requested changes
Я відішлю svg, додаш їх, тоді повністю merg'ну твою гілочку в main

2024-03-24 13:05 UTC, Nekit2501 reviewed
fix class

2024-04-13 09:03 UTC, merged